### ISSUE TITLE
Error on Device Update

### ISSUE THREAD

**Issue by Vanongart** [DarwinsBuddy/WienerNetzeSmartmeter#1]
After adding the Integration & entering my UN/PW; I don't get any new Entities in HA - but some errors in the Log.
(I only did opt into the 15 minute interval yesterday & the values do look pretty strange/off in the wienerNetze online portal).

Screenie from the online portal:
![image](https://user-images.githubusercontent.com/17415946/186107788-79f6d78e-dac5-43ba-bbe9-0bc6c94c1a18.png)
(did defenitly not use 7000 kWh yesterday; probably the smart meter returned the aggregated usage since its installation in feb 2020?; before yesterday I have no measurements at all)

Screens of the error message:
![image](https://user-images.githubusercontent.com/17415946/186105397-80c5fa19-ab39-4f8e-85a6-bf1a8c1d0740.png)

![image](https://user-images.githubusercontent.com/17415946/186105025-2108cc81-adec-4b03-9878-f7fb69d13dd3.png)

**Comment by DarwinsBuddy** [comment]
thanks for reaching out.
This is some odd behaviour.
The entities might not show up because the API responds with some unexpected payload.
This happened a lot during development tbh.
The integration expects on the welcome call a specific format.
I see two options here:

1) Remove the integration today and try to add it tomorrow again. (Maybe then there are more values to fetch and the problem resolves itself)

2) Which I'd prefer regardless of Option 1)
If you're okay with sending some more data I can look into your specific problem.
In your preferred Browser Open a New Tab -> Open DevTools (F12) -> Click on "Network" tab in devtools -> login and go to your smart meter portal -> after loading the overview page you'll see all api calls made by the page, look for the call in the Network Tab in DevTools similar to `/welcome` -> Click on it and Navigate in the small tabs beside it on `Response` -> copy the content and send it to me.

If you're worried about your privacy, delete your personal data from the payload, and either post it here, or send me a msg on keybase or per email christoph.spoerk@gmail.com

Thanks a lot for reporting this :)

**Comment by Vanongart** [comment]
Sure no problem:

Here's the /welcome api result:

```
{
    "hasSmartMeter": true,
    "isDataDeleted": false,
    "dataDeletionTimestampUTC": null,
    "zaehlpunkt": {
        "zaehlpunktName": null,
        "zaehlpunktnummer": "AT001XXXXXXXXXXXXXXXXXXXX",
        "zaehlpunktAnlagentyp": "TAGSTROM",
        "adresse": "XXXXXXXXXXXXXXXXXXXXXXXXX",
        "postleitzahl": "XXXXX",
        "meterReadings": [],
        "pmaxReadings": [
            {
                "value": 0,
                "type": "1-1:1.6.0",
                "validated": false,
                "startDate": null,
                "endDate": null,
                "range": "DAY"
            },
            {
                "value": 0,
                "type": "1-1:1.6.0",
                "validated": false,
                "startDate": null,
                "endDate": null,
                "range": "MONTH"
            }
        ],
        "consumptionYesterday": null,
        "consumptionDayBeforeYesterday": null,
        "optOutDetails": {
            "isOptOut": false
        }
    }
}
```
Maybe also interesting - the response for \VerbrauchRaw:
```
{
    "quarter-hour-opt-in": true,
    "values": [
        {
            "value": 6949,
            "timestamp": "2022-08-21T22:00:00.000Z",
            "isEstimated": false
        }
    ],
    "statistics": {
        "maximum": 6949,
        "minimum": 6949,
        "average": 6949
    }
}
```
Sure - thanks for maintining this - love HA - but have no clue about python (c#/javascript dev here ;-) )

**Comment by DarwinsBuddy** [comment]
that's interesting. seems like your Smartmeter has not enough data to provide you with yesterday's total energy consumption.

I'm unfortunately not able to predict the API behavior, but what I can and will do is making the integration more stable with respect to responses of that kind (i.e. `null` values in some sensor relevant fields).

this could've been a test case, but my lazy bum decided to go first for a quick win in implementing this integration. I'll probably have to dig into how HA integrations can be tested before I am able to decrease the probability of this happening.

anyways, I guess in a few days (or even tomorrow) you'll be able to retrieve your Smartmeter data. if not, please let me know (and of course Wiener Netze).

**Comment by Vanongart** [comment]
Hey, now I do have more data in my welcome api response - still no luck with the HA integration though:

My /welcome api response:
```
{
    "hasSmartMeter": true,
    "isDataDeleted": false,
    "dataDeletionTimestampUTC": null,
    "zaehlpunkt": {
        "zaehlpunktName": null,
        "zaehlpunktnummer": "AT0010000000000000001XXXXXXX",
        "zaehlpunktAnlagentyp": "TAGSTROM",
        "adresse": "XXXXXXXXXXXXX",
        "postleitzahl": "XXXXX",
        "meterReadings": [],
        "pmaxReadings": [
            {
                "value": 0,
                "type": "1-1:1.6.0",
                "validated": false,
                "startDate": null,
                "endDate": null,
                "range": "DAY"
            },
            {
                "value": 0,
                "type": "1-1:1.6.0",
                "validated": false,
                "startDate": null,
                "endDate": null,
                "range": "MONTH"
            }
        ],
        "consumptionYesterday": {
            "value": 6821,
            "validated": true,
            "date": "2022-08-23T22:00:00.000Z"
        },
        "consumptionDayBeforeYesterday": {
            "value": 7900,
            "validated": true,
            "date": "2022-08-22T22:00:00.000Z"
        },
        "optOutDetails": {
            "isOptOut": false
        }
    }
}
```

The Error:
![image](https://user-images.githubusercontent.com/17415946/186604220-cce89b32-0b8e-475d-8802-3dfe198e21d7.png)

Hope it helps with debugging ;-)

**Comment by DarwinsBuddy** [comment]
you're awesome. the data provided helps me out a lot. I hope I'll come to updating the integration in the next couple of days.

**Comment by DarwinsBuddy** [comment]
Please upgrade your integration and report back if it still doesn't show an entitiy.
If you're not getting any meter readings, please file another issue. (I guess that Wiener Netze did not provide data already in the time being, but hopefully do as of now)
