### ISSUE TITLE
outgoing electricity not counted

### ISSUE THREAD

**Issue by mochitoju** [DarwinsBuddy/WienerNetzeSmartmeter#10]
incoming is working good.
2nd "Zählerpunkt" is regonised but shows no data
(outgoing electricity from photvoltaik modules)
![Unbenannt](https://user-images.githubusercontent.com/76213255/194764489-1eccf81e-4003-46f5-a2b2-261cfd1e6bc7.JPG)

**Comment by DarwinsBuddy** [comment]
You can disable sensors in hassio if not needed. I myself have an old one from my former flat in there, which is not providing any data (oc).

**Comment by mochitoju** [comment]
Thank you for your fast reply. This one DOES HAVE some data, but its not shown!

**Comment by DarwinsBuddy** [comment]
Unfortunately, I do not have a photvoltaik module and cannot provide an integration for it. If you have the time you can provide a PR for integrating this as an additional sensor. (I guess the returned payload from the API differs from the SmartMeter ones, as it's an outgoing connection)

**Comment by mochitoju** [comment]
confused - if i go to "https://smartmeter-web.wienernetze.at" i can see both "counter" and can switch. 
If i install your integration it imports BOTH "counter" (see picture on top) but the second "counter" not showing any datas. 
The only difference is "Zählertyp": Tagstrom & Einspeiser
On the Wiener Netze Website you can select/switch between this two "counters".

**Comment by DarwinsBuddy** [comment]
The whole integration uses the WienerNetze Smartmeter API, which is not publicly documented or open-source. So every payload I am retrieving, every call I make in that integration is an assumed one and can change anytime in the future. Also my interpretation of the data is based upon assumption. Such as, that every returned "Zähler" is one that counts consumption.
If you somehow can send me the response (from your Browsers Network tab) of the welcome or daily_usage call, I can at least exclude the sensor for now. If you can offer even more detailed information, I could also try to integrate the other "Zählertyp".
If you're interested you can drop me an email and we can figure out how to proceed further. Only issue here is: without an account containing a "Tagstrom & Einspeiser", which I do not have, it's going to be impossible for me to foresee the responses of the not-documented API.
