### ISSUE TITLE
Sensor not shown on energy dashboard

### ISSUE THREAD

**Issue by ralpho1337** [DarwinsBuddy/WienerNetzeSmartmeter#11]
Hi teams,

thanks for developing this integration.

I get a correct value for sensor.at001xxx but it is not shown in my engery dashboard.

How can I get it to be shown there?

Thanks
Ralph

**Comment by DarwinsBuddy** [comment]
Go to https://<your-hassio-entrypoint>/config/energy and add it. It's something you should ask next time in the hassio community, though.
