### ISSUE TITLE
Docu - can you explain how the new _statistics attribute works?

### ISSUE THREAD

**Issue by GeraldPape** [DarwinsBuddy/WienerNetzeSmartmeter#118]
How can we use the new _statistics attribute in the energy tab?

How long in the past is the data loaded from?

**Comment by DarwinsBuddy** [comment]
@reox Could you update https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/discussions/19 to cover this? :upside_down_face:

**Comment by reox** [comment]
done!
