### ISSUE TITLE
Entität nicht definiert / not defined

### ISSUE THREAD

**Issue by GeraldPape** [DarwinsBuddy/WienerNetzeSmartmeter#119]
Added the attribute to the energy tab, receiving the following error:
![grafik](https://user-images.githubusercontent.com/72608781/234248639-f517b675-5b9b-49a1-87d6-4836edaf3635.png)

for reference:
in the smart meter portal the "newest" data for my smart meter is from 15 days ago.
My data history starts on the 24. February 2023

**Comment by reox** [comment]
>  in the smart meter portal the "newest" data for my smart meter is from 15 days ago.

If there is no data in the smartmeter-web, it cannot be imported into HA. We use the same API as the smartmeter-web does...

Other than that, this warning should not matter and statistics should still be imported.
