### ISSUE TITLE
Fill holes of statistics data

### ISSUE THREAD

**Issue by reox** [DarwinsBuddy/WienerNetzeSmartmeter#140]
Detached from here: https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/pull/89#issuecomment-1542416544

The problem can be, that measurements are delayed in the API and the next day enters the system earlier than the previous day.
That could then lead to days missing consumption data.

The biggest question is how they could be added, as the statistics import does not really allow to insert data between already inserted data.
One proposed idea was to delete all imported data back to the missing date and then start the import again.

**Comment by salzrat** [comment]
Any further ideas on this?
