### ISSUE TITLE
v1.1.0 --> statistics_sensor --> list index out of range

### ISSUE THREAD

**Issue by acdcnow** [DarwinsBuddy/WienerNetzeSmartmeter#143]
Hi @DarwinsBuddy 

I go a new smart Meter with customer interface and I get now the below message on the statistic sensor.
Not sure if the change is related to I guess not.
I use as well 15 mins value in the Smart meter Portal.

Error message is given as.

Logger: homeassistant.components.sensor
Source: custom_components/wnsm/statistics_sensor.py:179
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 23:43:55 (1 occurrences)
Last logged: 23:43:55

wnsm: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_device_update
    await self.async_update()
  File "/config/custom_components/wnsm/statistics_sensor.py", line 126, in async_update
    await self._import_historical_data(smartmeter)
  File "/config/custom_components/wnsm/statistics_sensor.py", line 179, in _import_historical_data
    _LOGGER.debug(f"Importing statistics from {statistics[0]} to {statistics[-1]}")
IndexError: list index out of range

**Comment by DarwinsBuddy** [comment]
@reox I guess we have an out of bounds error.

@acdcnow I guess there is no historical data for now, as your smart meter is brand new. wait for a couple of days and report back afterwards.

**Comment by reox** [comment]
I see, that should be an easy fix: There were no values returned, and thus the array is empty.

**Comment by acdcnow** [comment]
lets try , according to the smart meter homepage here are historical data so that should not be the issue in this case.
The smart meter is now already 1 1/2 month in use and active.
I added your correction into and the statistic sensor is at least created. Need to the same same into the recorder and history. Lets see if I get here any useful statistic data.

**Comment by reox** [comment]
If you download the CSV on the smartmeter web page, does it contain any data? Maybe the issue is, that this data is inserted only later...
