### ISSUE TITLE
showing consumption differently

### ISSUE THREAD

**Issue by andjona** [DarwinsBuddy/WienerNetzeSmartmeter#166]
I have three meters connected to ha via two different accounts.
![sm](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/38523314/c958005f-ea36-4a90-a2f1-347f16ecf46c)
T3 is running on the first account and shows the total consumption of the meter.

T14 running on the second account is defined in the "Wiener Netze Smart Meter portal" as "Favorit" and also shows the total consumption.
T7 is also running on the second account and shows the consumption of the last day (what i like much better than showing the total consumption). When setting this one to "Favorit" the behavior of Meter T14 and T7 flips.

Is there a way of only showing yesterdays consumption?
Thanks for your help,
Andreas

**Comment by reox** [comment]
You can do this with lovelace widgets: https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/discussions/19
or do you want something different?
