### ISSUE TITLE
Error in live_sensor: "Please file an issue with this error[...]"

### ISSUE THREAD

**Issue by simmac** [DarwinsBuddy/WienerNetzeSmartmeter#203]
I still don't get data from the integration, and the integration is reporting the following error:

> ```Please file an issue with this error and (anonymized) payload in github {'hasSmartMeter': True, 'isDataDeleted': False, 'zaehlpunkt': 'AT001[redacted]', 'type': 'TAGSTROM', 'address': '[redacted]', 'zip': '[redacted]'} {'consumptionDayBeforeYesterdayValue': 13749, 'consumptionDayBeforeYesterdayValidated': True, 'consumptionDayBeforeYesterdayTimestamp': '2023-12-14T23:00:00.000Z'} {} {'optIn': True, 'consumptionAverage': 0, 'consumptionMinimum': 0, 'consumptionMaximum': 0}```

> ```Please file an issue with this error and (anonymized) payload in github {'hasSmartMeter': True, 'isDataDeleted': False, 'zaehlpunkt': 'AT0010[redacted]', 'type': 'TAGSTROM', 'address': '[redacted]', 'zip': '[redacted]'} {'consumptionYesterdayValue': 7691, 'consumptionYesterdayValidated': True, 'consumptionYesterdayTimestamp': '2023-12-15T23:00:00.000Z', 'consumptionDayBeforeYesterdayValue': 13749, 'consumptionDayBeforeYesterdayValidated': True, 'consumptionDayBeforeYesterdayTimestamp': '2023-12-14T23:00:00.000Z'} {} {'optIn': True, 'consumptionAverage': 0, 'consumptionMinimum': 0, 'consumptionMaximum': 0}```

**Comment by DarwinsBuddy** [comment]
same as #204
