### ISSUE TITLE
No values in API response

### ISSUE THREAD

**Issue by reox** [DarwinsBuddy/WienerNetzeSmartmeter#204]
Since December 16th and with v1.4.1 I get this error:
```
 No values in API response! This likely indicates an API error. Original response: {'optIn': True, 'consumptionAverage': 0, 'consumptionMinimum': 0, 'consumptionMaximum': 0} 
```

Anyone else seeing this? @DarwinsBuddy Has the API changed once more?
There are values in the WN Dashboard...

**Comment by DarwinsBuddy** [comment]
as I changed it on the weekend I got back the right values. I guess I've to again get rid of calls to `/verbrauchRaw` in favor of `/verbrauch` as it's not reliable.

I hope I get to it this week. maybe even today

**Comment by Sup3rMario** [comment]
i have the problem too!

**Comment by mundschenk-at** [comment]
Looks like the update is not working for a lot of people. Has anyone tested reverting to the previous release?

**Comment by Sup3rMario** [comment]
Hello together,

Unfortunately I can't go back. But here are my data:

wnsm version 1.4.1, installed on December 16, 2023 10:46 p.m

HA see print screens

 

Von: Der Mundschenk & Compagnie ***@***.***> 
Gesendet: Samstag, 23. Dezember 2023 07:13
An: DarwinsBuddy/WienerNetzeSmartmeter ***@***.***>
Cc: Mario Linhart ***@***.***>; Comment ***@***.***>
Betreff: Re: [DarwinsBuddy/WienerNetzeSmartmeter] No values in API response (Issue #204)

 

Looks like the update is not working for a lot of people. Has anyone tested reverting to the previous release?

**Comment by reox** [comment]
I think I see the problem. The endpoint returns no `values` key when there is no data - before that meant something is wrong. now this just means, that there is no data yet.
Removing the return from `_import_statistics` should fix it.
I'm testing this right now!

**Comment by reox** [comment]
huh, why do I only get daily data now?! Okay, so something else has changed too :/

However, the import is working again in principle ^^

**Comment by reox** [comment]
There is even a (hacky) way to remove statistics and re-import hourly ones (might also be a trick for later...)

with SQLite Web installed, first query the metadata_id of the statistics sensor, by looking into the date `statistics_meta`. Mine was 49. Then delete all statistics data starting from some timestamp:
```
delete FROM "statistics" where metadata_id = 49 and start_ts >= 1702508400;
```
