### ISSUE TITLE
Only one entity added. _statistics entity is missing

### ISSUE THREAD

**Issue by markush97** [DarwinsBuddy/WienerNetzeSmartmeter#207]
I have 15 minute reports enabled with wiener-netze.
I deleted all statistics as explained in the FAQ und readded the integration twice. Still there is only one entity and no hourly statistics.

What am I doing wrong?

Thanks in advance!

**Comment by markush97** [comment]
I am on version 1.4.1

**Comment by MatthiasRei** [comment]
The actual version 1.4.1 is not working because Wiener Netze changed the API #204. You are doing nothing wrong 🙂

**Comment by reox** [comment]
you can test with my changes in #206
