### ISSUE TITLE
Invalid handler specified after trying to add the integration

### ISSUE THREAD

**Issue by ldoench** [DarwinsBuddy/WienerNetzeSmartmeter#21]
After adding the module in hacs and trying to add the integration I get following error:

`Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}`

And in the logs I get:
```
Logger: homeassistant.config_entries
Source: config_entries.py:809
First occurred: 10:50:57 (1 occurrences)
Last logged: 10:50:57

Error occurred loading configuration flow for integration wnsm: No module named 'lxml'
```

Also for manual configuration I get `Platform error sensor.wnsm - No module named 'lxml'`

**Comment by DarwinsBuddy** [comment]
are you sure you added this repository and not a fork?

**Comment by DarwinsBuddy** [comment]
oh wow. thanks for pointing that out. seems I made a mistake by setting up the HACS github action

**Comment by DarwinsBuddy** [comment]
I'll close this now, feel free to reopen if the issue persists after updating

**Comment by ldoench** [comment]
I removed it, added it again, cleared the cache and restarted HA, but still get the same error. 

As i see, you just edited the github actions, but none of the code itself?

**Comment by DarwinsBuddy** [comment]
I did, as someone forked the project and accidentally HACS thought there is
a new version (presumably). Can you look up on which version (should be a
commit hash) your integration is currently at?

**Comment by ldoench** [comment]
It's e1ff55d from you (@DarwinsBuddy)

Also it's weird, cause I also get this error after I moved your code manually to the custom_components folder

**Comment by DarwinsBuddy** [comment]
hmmm. could bet that I forgot to add `lxml` as a requirement, which was already pre installed by many other users anyways.

https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/commit/6262f7026d968571d7e71747210eed3d819c81e5

Thanks https://github.com/lumpi1982 for implicitly trying to fix it in https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/pull/14

**Comment by DarwinsBuddy** [comment]
there should be an update available for HACS, could you try to install it on more time? (remove and re-install if a simple update doesn't work)

**Comment by ldoench** [comment]
Now it works. Thank you for your help

**Comment by DarwinsBuddy** [comment]
Thanks for being tenacious :) I'm happy that I found the bug thanks to you. Have a nice Sunday ;)
