### ISSUE TITLE
Einspeisezählpunkt wird gefunden aber keine Daten

### ISSUE THREAD

**Issue by nkk67** [DarwinsBuddy/WienerNetzeSmartmeter#213]
Ich habe seit kurzen einen zweiten Zählpunkt zum Einspeisen. Der wird zwar gefunden, aber keine Daten geladen. Mein anderer Zählpunkt funktioniert ohne Probleme.

**Comment by DarwinsBuddy** [comment]
I released a new version with some fixes to the statistics import.
Please remove the whole integration once and reinstall it.
I'll close this ticket, please reopen a new ticket when the issue still persists.
