### ISSUE TITLE
after update 1.4.3 statistic entity is not working

### ISSUE THREAD

**Issue by 2023alpha2023** [DarwinsBuddy/WienerNetzeSmartmeter#214]
After the update 1.4.3 the statistic entity is not working any more.

In the home assistent energy dashboard incorrect values are shown.
e.g.: there is no hourly data available
An incorrect value e.g. 0.7 kWh is shown

**Comment by DarwinsBuddy** [comment]
I released a new version with some fixes to the statistics import.
Please remove the whole integration once and reinstall it.
I'll close this ticket, please reopen a new ticket when the issue still persists.
