### ISSUE TITLE
since middle of January statistic entities are not working 

### ISSUE THREAD

**Issue by 2023alpha2023** [DarwinsBuddy/WienerNetzeSmartmeter#216]
hi again,
the new version 1.4.5 didn't solve the problem.
Until around 17.01.24 I got this data in the home assistent energy dashboard (I add two statistic entities)
<img width="771" alt="Bildschirmfoto 2024-01-29 um 20 09 11" src="https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/157567331/136df6d0-9563-40cc-856e-b43b094fb8e4">
Everything is fine, Verbrauch and Netzeinspeisung are working
Yellow bar: data from an solar inverter

since 18.01.24 both statistic entities are not working and I got unclear data e.g.:
<img width="771" alt="Bildschirmfoto 2024-01-29 um 20 10 21" src="https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/157567331/7d2730c3-ba76-4a27-a013-9e0615510fe9">
Three bars for Verbrauch, rest is missing
Netzeinspeisung: no bar

Is there any idea or trick to solve the problem?
If I remember correctly version 1.4.0 or 1.4.1 was working. I tried a couple of things:
- delete the entities
- delete the folder in custom_components
- installed version 1.4.0 or 1.4.1
- installer the actual version

-> no impact, still unclear data

**Comment by manolitto** [comment]
have a similar problem:
- version 1.4.5
- completely uninstalled the integration and deleted all old data
- reinstalled and reconfigured everything a week ago (when 1.4.5 came out)
- historic data (statistics) loading worked ok (once after setup), but
- on the next day I had a huge negative "consumption"
- and from next day on I **get no data any longer at all**

![Screenshot 2024-02-01 at 21 21 54](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/6802880/2ee3ce11-52e4-4b86-b92c-36b5915d3d33)

![Screenshot 2024-02-01 at 21 22 11](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/6802880/00815a28-a6ea-42f4-bc37-9c37bf3013f6)

**Comment by simmac** [comment]
Similar issue for me. Look into your logs to see whether you get the same message, this is what I see in my logs:

`Unable to load consumption`

```Please file an issue with this error and (anonymized) payload in github {'hasSmartMeter': True, 'isDataDeleted': False, 'zaehlpunkt': 'AT0010000000000000001000000[redacted], 'type': 'TAGSTROM', 'address': '[redacted]', 'zip': '[redacted]'} {'consumptionYesterdayValue': 10569, 'consumptionYesterdayValidated': True, 'consumptionYesterdayTimestamp': '2024-01-28T23:00:00.000Z', 'consumptionDayBeforeYesterdayValue': 14475, 'consumptionDayBeforeYesterdayValidated': True, 'consumptionDayBeforeYesterdayTimestamp': '2024-01-27T23:00:00.000Z'} {} {'optIn': True, 'consumptionAverage': 0, 'consumptionMinimum': 0, 'consumptionMaximum': 0}```

**Comment by tixoman** [comment]
had the same problem.
My solution: deleting the 0 entries in the recorder database every day.

DELETE 
FROM statistics 
WHERE metadata_id IN (
	SELECT ID FROM statistics_meta WHERE statistic_id LIKE '%AT00%'
)
AND state = 0 AND SUM = 0 AND start_ts >= UNIX_TIMESTAMP( DATE_ADD( UTC_DATE(), INTERVAL -1 DAY) ) 

So i have no negative consumption and the import is also running correct every day.

**Comment by DarwinsBuddy** [comment]
Please upgrade to [v1.4.6](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/releases/tag/v1.4.6) and follow instructions in [FAQs](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/discussions/19) `How can I start over with a fresh data import?`

**Comment by manolitto** [comment]
> Please upgrade to [v1.4.6](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/releases/tag/v1.4.6) and follow instructions in [FAQs](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/discussions/19) `How can I start over with 
a fresh data import?`

Hmm, I upgraded and followed the FAQ guide (btw. small typo there, guess it should be "Days to keep"  instead of "Days to remove"?)
After a restart and the reinstall of the integration everything looked fine.
A little later after another restart (actually a reboot) the Energy Board again shows a huge negative consumption for today (!?).

Will report what happens tomorrow after the next data import run...

**Comment by lukas-berger** [comment]
Same here, followed the guide in the FAQ and seeing -1096.2 kWh consumption for today.

**Comment by stefanschramek** [comment]
I have the same issues, as mentioned here https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues/219
