### ISSUE TITLE
Energy Dashboard shows feeding without actually feeding in place

### ISSUE THREAD

**Issue by stefanschramek** [DarwinsBuddy/WienerNetzeSmartmeter#219]
Hi,
as I had some issues the last days - missing data points and if they are shown it was wrong data, I deleted the integration and historical data and started from scratch.
Everything showed as correct, but now I realized that it shows that I seemed to feed around 12kwh today. But I do not feed energy at all.
<img width="1178" alt="energy" src="https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/921342/14234eda-123a-4e38-bd66-fc8066979959">
I found this entry - it is around the time when I setup the integration
<img width="483" alt="energy_stat" src="https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/921342/9f400c64-c7f9-4177-96c2-2d26b9a1b22d">
It seems there is some calculation wrong imho.
TIA

**Comment by maparth** [comment]
+1

**Comment by 2023alpha2023** [comment]
same issue. I followed the FQA (How can I start over with a fresh data import?), for 2 days this approach was working.
But there is a new issue:
I have two Zählpunkte:
Zählpunkt 1: two entities (normal and statistic)
Zählpunkt 2: one entity (just the normal one).

<img width="933" alt="Bildschirmfoto 2024-02-12 um 20 15 06" src="https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/157567331/9e318b7c-43cd-4d82-bdc8-728d1652fd5f">
(blue: consumption, yellow: production: missing: Feed-in, in January this was working)


Furthermore, when I set Zählpunkt 1 in the smart meter portal, in Home Assistent the kWh is only shown for Zählpunkt 1, no data is shown for Zählpunkt 2.
When I set Zählpunkt 2 in the smart meter portal, in Home Assistent the kWh is only shown for Zählpunkt 2, no data is shown   for Zählpunkt 1

**Comment by andreasgily** [comment]
![Bildschirmfoto von Google Chrome am 13_02_2024, 12_12_38](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/88045222/292170cf-dcc6-488e-9016-a392d823221c)

I have a similar problem here - I cleaned my database of the old stats data, which worked perfectly - wnsm re-imported all the missing stats after a restart, but now I somehow got a negative value at lunchtime today (there shouldn't be any stats available, only from yesterday). I suspect there is some misinterpretation of the API happening somehow?

**Comment by adamnet01** [comment]
The same thing happens to me after reloading the integration.  This problem has been occurring since the beginning of this year.
![Screenshot_20240213_172436_Home Assistant](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/91046662/3db23b3b-f0f7-4add-b7f5-da2836aeb785)

**Comment by mgmomo** [comment]
Hi,
I have the same problems. I have removed the integration according to the FAQ. After a new setup, there are zero values in the database and it looks like the difference between the last regular total value and the zero value is displayed as a negative bar. With the zero values there is no update on the following days.

![image](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/6432994/8c16ce8d-8e71-438f-9c12-6688393bb49d)

![image](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/6432994/ea0b3f7d-2009-4d05-b7e4-bd84cdb93819)

**Comment by rolandpj** [comment]
I have this issue since Version 1.4.1. Version 1.4.0 was the last version that worked fine

**Comment by codegain** [comment]
Same here, Version 1.4.0 is the last working version for me. I upgraded to all versions from 1.4.1 to the latest (1.4.6). Some of them import the historical data correctly, but don't update them anymore (= days of just empty data).

And some of the later versions add a huge negative kWh usage right after importing the historical data. I followed the FAQ, purged all the data, sensors, entites etc., restarted and reinstalled the integration.

**Comment by salzrat** [comment]
I have the same problem. 1.4.6. I suddenly got a -20kwh negative bar, and no input since then. Also followed the FAQ on reimporting, didn't do anything. Still no data after Feb 14, except for some huge negative bars on some days...

**Comment by salzrat** [comment]
has anybody tried going back to 1.4.0? Does this solve the problem?

**Comment by stefanschramek** [comment]
> has anybody tried going back to 1.4.0? Does this solve the problem?

Not yet - I thought it is just a quick fix and worth to wait for it!

**Comment by rolandpj** [comment]
I did it a couple of times... upgraded to 1.4.2 and went back to 1.4.3 and went back... worked all the time. But after 1.4.6 i also tried to go back but I am not able to get it running again because statistics entity is not beeing created
Unfortunately version selector of HACS does not offer 1.4.0 and it has to be done manually

**Comment by salzrat** [comment]
so currently no way to get it running again?

**Comment by reox** [comment]
I never updated on my HA and still use 8a45fc1c68ee9c3d41212831ae9f5c17bdc93cb7
At least that version is working for me. This bug seems to be introduced with one of the commits after that.
One could try to git-bisect, however it would be a tedious debugging, as you had to wait a day for new data, right?

**Comment by salzrat** [comment]
Interesting. So for me 1.4.0 (and I believe 1.4.1, still have to check) produce fresh data. Haven't tried wiping the old data yet.
But 1.4.2 produces:
`Logger: homeassistant.loader
Source: loader.py:847
First occurred: 12:46:52 (1 occurrences)
Last logged: 12:46:52

Unexpected exception importing platform custom_components.wnsm.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 847, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 864, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/wnsm/sensor.py", line 26, in <module>
    from .statistics_sensor import StatisticsSensor
  File "/config/custom_components/wnsm/statistics_sensor.py", line 7, in <module>
    from .base_sensor import BaseSensor
  File "/config/custom_components/wnsm/base_sensor.py", line 31, in <module>
    class BaseSensor(SensorEntity, ABC):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 414, in __init__
    wrap_attr(cls, property_name)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 386, in wrap_attr
    raise TypeError(f"Can't override {attr_name} in subclass")
TypeError: Can't override _attr_state_class in subclass
`

**Comment by reox** [comment]
Yep, there were some regressions introduced in the meantime. 

However, I do not understand what is going on... It is some homeassistant thing and I saw this behaviour too when testing: It happenend if the state of the statistics sensor was set to 0. Then, HA assumes that all the statistics were compensated and added this negative number. However, we do not do this - or do we? Do I miss something?

**Comment by salzrat** [comment]
I have no idea, but the problem is that afterwards, no new values are reported anymore...

**Comment by reox** [comment]
Oh, wait! https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/commit/821b76d84f148b31695e52c217a55b0249de912f

https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/blame/2aeed69e52595e7157b06a579eeef739f242838a/custom_components/wnsm/statistics_sensor.py#L131

This might be the issue. Can you try to just comment out this line?

**Comment by salzrat** [comment]
in which version?

**Comment by codegain** [comment]
@reox I did completely purge the data (described in the FAQ), installed v1.4.6, commented out that line + restart. Then did a fresh historical import of the data (up to 29.2.2024)

So far all historical data has been correctly imported with no negative kwh entries in the energy dashboard. Will report back tomorrow if data is being correctly imported for 1.3.2024.

**Comment by reox** [comment]
> in which version?

In master, i.e. 1.4.6

> @reox I did completely purge the data (described in the FAQ), installed v1.4.6, commented out that line + restart. Then did a fresh historical import of the data (up to 29.2.2024)

sounds good!

**Comment by salzrat** [comment]
Amazing, this works! After deleting as described in the FAQ, all the historic data is is imported correctly! Holding fingers crossed for import tomorrow :)

**Comment by 2023alpha2023** [comment]
I can also confirm that the purge, as described in the FAQ works. Hopefully longer than one day. I have still an other issue, my second zählerpunkt is not working. This is also strange due to the fact that these zählerpunkt was also working with an old version

**Comment by codegain** [comment]
> So far all historical data has been correctly imported with no negative kwh entries in the energy dashboard. Will report back tomorrow if data is being correctly imported for 1.3.2024.

@reox Can confirm your proposed change in v1.4.6 solves the negative kwh and also imports fresh data. As of today I have data for 1.3.2024. Thanks!

**Comment by salzrat** [comment]
Same here, works!

**Comment by 2023alpha2023** [comment]
@salzrat : how die you managed this? I purge the data according to the fqa  but i got negative values. I use Version 1.4.6.

**Comment by salzrat** [comment]
Comment out the line indicated by @reox before reinstallation (in the wnsm installation subdirectory in the homeassistant config directory).

**Comment by codegain** [comment]
@2023alpha2023 I used the "File editor" Addon (installable via settings -> addons). Then open it and simply navigate to `custom_components/wnsm/statistics_sensor.py`, find line 131 and add a `#` before it. Save + restart Home Assistant (or just edit the file the way you're familiar with).

**Comment by stefanschramek** [comment]
Thank you for your effort, guys!!!
Very much appreciated!

**Comment by 2023alpha2023** [comment]
> @2023alpha2023 I used the "File editor" Addon (installable via settings -> addons). Then open it and simply navigate to `custom_components/wnsm/statistics_sensor.py`, find line 131 and add a `#` before it. Save + restart Home Assistant (or just edit the file the way you're familiar with).

thank perfekt it works.
I have still the second issue. I have two zähler punkte but only 3 entities. The statistic entity für the second zählerpunkt is missing.

**Comment by W-M-B** [comment]
> The same thing happens to me after reloading the integration. This problem has been occurring since the beginning of this year. ![Screenshot_20240213_172436_Home Assistant](https://private-user-images.githubusercontent.com/91046662/304480111-3db23b3b-f0f7-4add-b7f5-da2836aeb785.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTQ2MTEsIm5iZiI6MTcwOTc5NDMxMSwicGF0aCI6Ii85MTA0NjY2Mi8zMDQ0ODAxMTEtM2RiMjNiM2ItZjBmNy00YWRkLWI3ZjUtZGEyODM2YWViNzg1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA2NTE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NjU4MTExZDM1NWU4MjcxN2U5ODE3NzE5M2M1ODQ2MWZmMDhjZDkxZWE0ODc3MTU5ZDU4MzA5NzNkOGY0MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EGIC8c-vJci0p5YpXygf6aIB2jmRxvgSyX-WBpM62gw)

Same here:
I had issues in January, upgraded to the latest version.
First loading was good, then I had the same issues s other mentioned.
I deleted everything according to the faq section.
But no improvement:
First loading is good. All data later on after initial load is wrong. Currently I cannot use the integration 😞.

**Comment by rolandpj** [comment]
> > The same thing happens to me after reloading the integration. This problem has been occurring since the beginning of this year.
> 
> Same here: I had issues in January, upgraded to the latest version. First loading was good, then I had the same issues s other mentioned. I deleted everything according to the faq section. But no improvement: First loading is good. All data later on after initial load is wrong. Currently I cannot use the integration 😞.

This seems to be fixed and fix is confirmed by a couple of users.. just waiting for the release :-)
