### ISSUE TITLE
Username/password invalid

### ISSUE THREAD

**Issue by joshua1000** [DarwinsBuddy/WienerNetzeSmartmeter#22]
Hi,
I'm having issues with the login, immediately after adding the integration.
I've successfully copied the custom components over, found it in HACS, downloaded, restarted and tried to add the integration under the "Devices and Integrations" tab in Home Assistant.
The credentials I'm using work fine when logging in directly on the website, but I get an error "Username/password invalid" when using the same credentials for the integration.
What am I doing wrong?
Thanks!!

**Comment by DarwinsBuddy** [comment]
Please first consult the [FAQ](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/discussions/19). Reopen this issue if that doesn't solve your problem.

**Comment by joshua1000** [comment]
I'm sorry, I should have made this clearer. I am not using any sort of oauth, but an email and password directly when logging in via https://smartmeter-web.wienernetze.at/ 
The same credential are rejected by the integration.
