### ISSUE TITLE
Subsequent update to statistics after initial import is not working

### ISSUE THREAD

**Issue by patakfal** [DarwinsBuddy/WienerNetzeSmartmeter#222]
I have the following issue  on version 1.4.6. After a successful import at the beginging of a new integration works perfectly with the change of self._state = None in statistics_sensor.py. No negative value.
 But I get no update after that even after 2 days... API calls are happening every hour but it does not update statistics. Does anyone have the same issue? Log attached
[wienenergie.log](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/files/14537638/wienenergie.log)

**Comment by ziggypin** [comment]
same issue here

**Comment by real-alphamaennchen** [comment]
Have the same issue.

**Comment by real-alphamaennchen** [comment]
The manual fix from #219 seems to fix my problem

**Comment by DarwinsBuddy** [comment]
release incorporating the fix is on its way :rocket:

**Comment by patakfal** [comment]
I do not think it solved the issue. I started mine with the comment that self._state = None was changed, which you implemented in 1.4.7.  As said even after the change I had no subsequent update... So I would not consider this closed.
