### ISSUE TITLE
HomeAssistantType was used from wnsm, this is a deprecated alias which will be removed in HA Core 2025.5

### ISSUE THREAD

**Issue by GeraldPape** [DarwinsBuddy/WienerNetzeSmartmeter#231]
Logger: homeassistant.helpers.typing
Quelle: helpers/deprecation.py:206
Erstmals aufgetreten: 11:45:06 (1 Vorkommnisse)
Zuletzt protokolliert: 11:45:06

HomeAssistantType was used from wnsm, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'wnsm' custom integration

**Comment by reox** [comment]
See https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/pull/229/files

**Comment by DarwinsBuddy** [comment]
thanks @reox

merged :heavy_check_mark:
