### ISSUE TITLE
Change password for integration

### ISSUE THREAD

**Issue by codegain** [DarwinsBuddy/WienerNetzeSmartmeter#235]
Hi,

I recently had to change my password for the LogWien login because I couldn't remember it. I couldn't find a way to change the password for the integration.

I there any way to change the password without removing and reinstalling the integration?

**Comment by tschoerk** [comment]
You can edit the file `<home-assistant-root>\config\.storage\core.config_entries` (the folder .storage is hidden). There is an entry with the title Wiener Netze Smartmeter and right below are your credentials.

**Comment by codegain** [comment]
@tschoerk Thanks, that worked!
