### ISSUE TITLE
Statistics Zählpunk liefert keine Daten mehr

### ISSUE THREAD

**Issue by prnzngr** [DarwinsBuddy/WienerNetzeSmartmeter#239]
Der normale Zählpunkt liefert noch Daten aber der Statistics Zählpunkt nicht mehr
In den Logs finde ich keine Hinweise

![image](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/assets/11977124/6b8016e4-7d99-44c7-95fc-a926de665bd4)

**Comment by W-M-B** [comment]
Hallo,
schau mal in dem Smartmeter Portal der Wiener Netze. ich habe dasselbe Problem, mir fehlen aber auch die Stunden und 15 Min Werte im Portal. Bin das gerade am lösen mit den Wiener Netzen.

**Comment by peregrines2** [comment]
Bei mir das gleiche Problem.
Wenn ich dir Integration entferne und neu einrichte geht es jedesmal wieder für ein paar Tage.

**Comment by DarwinsBuddy** [comment]
Danke @peregrines2 @W-M-B für die Hilfe

Ich schließe das Issue wegen Inaktivität. Falls das noch einmal auftritt bitte ein Neues eröffnen.

**Comment by W-M-B** [comment]
can be closed, daten sind seit dieser Woche wieder da. und funktioniert.
falls es noch auftritt: ich habe im portal  meine ZP die 15/ Minuten taktung deaktiviert. 3-4 Tage gewartet.
und dann wieder aktiviert. das hat bei mir geholfen.
