### ISSUE TITLE
Hourly Data (statistics) with no data since 24.6.

### ISSUE THREAD

**Issue by GrumpyTed82** [DarwinsBuddy/WienerNetzeSmartmeter#243]
Hi, 

everything was working with the integration and the smart meter, but since 24.6. the statistics entity has no data.
I checked the "Zählpunkt" and there I have data, so its only the statistics entity. 

and I just don't know what changed from 23.6. to 24.6. 

maybe you guys have an idea?

**Comment by W-M-B** [comment]
See here:

https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues/239#issuecomment-2225136348

**Comment by DarwinsBuddy** [comment]
@GrumpyTed82 if above linked issue solves your problem please close this issue, or reply so I can close it.
Otherwise please describe why that didn't solve it

**Comment by GrumpyTed82** [comment]
I'm still trying to test it .. will give feedback if it will start working again (in the other thread, it says to wait few days)
