### ISSUE TITLE
Connection Error 

### ISSUE THREAD

**Issue by mgmomo** [DarwinsBuddy/WienerNetzeSmartmeter#246]
Hi,
since Wednesday, 31.7.2024, there was an API change at WienerNetze. In the "main.xxxxxxxxxx.js" file the API Key after "b2cApiKey" cant't be found anymore. 

This error is shown in Homeassistant:
"custom_components.wnsm.api.errors.SmartmeterConnectionError: Could not obtain API Key - no match"

**Comment by reox** [comment]
so either that is an temporary issue and goes away soon or they really changed something :( In that case one would have to check where we get the key from...

**Comment by reox** [comment]
Okay, maybe they really changed something. It looks like there is now a JSON file that contains the information: `https://smartmeter-web.wienernetze.at/assets/app-config.json`
Can someone verify that? If that is the case, it would be actually much easier to get the keys.

**Comment by mgmomo** [comment]
above fix #248 is working for me too. great! thx a lot!
