### ISSUE TITLE
Adding the component via configuration.yaml does not work with multiple zaehlpunkte

### ISSUE THREAD

**Issue by tschoerk** [DarwinsBuddy/WienerNetzeSmartmeter#255]
Originally issued by @akicker in https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues/227#issuecomment-2290980923_

PR will follow

**Comment by DarwinsBuddy** [comment]
new release [v1.5.3](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/releases/tag/v1.5.3) contains the fix :)
