### ISSUE TITLE
Statistical data is not updated

### ISSUE THREAD

**Issue by cnekola** [DarwinsBuddy/WienerNetzeSmartmeter#260]
Hi,

When I install the extension, I get the statistics data once. After that, the field is no longer updated.
Even a complete reinstallation did not help.

thx, Chris

**Comment by JinKanzaki** [comment]
Same

**Comment by acdcnow** [comment]
same

**Comment by tschoerk** [comment]
Is the data available in the smartmeter portal? I saw they had some problems providing the data in the last few weeks.
If it's available are there any error messages in the protocol?

**Comment by cnekola** [comment]
Hi,
Yes, the data is also available after a new installation. It is just not updated.
But only the statistic entity. The "main" entity gets data.

>> If it's available are there any error messages in the protocol?

how do i get this protocol?

thx

**Comment by h9lmut** [comment]
Similar for me.
The integration worked fine for a long time.
Aug. 14th statistics are not updated anymore. 

In the Liga I see the following error:
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:951
First occurred: September 15, 2024 at 00:36:41 (88 occurrences)
Last logged: 21:36:41

Update for sensor.at0010000000000000001000006031119_statistics fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1268, in async_device_update
    await self.async_update()
  File "/config/custom_components/wnsm/statistics_sensor.py", line 112, in async_update
    await self.hass.async_add_executor_job(smartmeter.login)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 125, in login
    code = self.credentials_login(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 75, in credentials_login
    raise SmartmeterLoginError("Login failed. Check username/password.")
custom_components.wnsm.api.errors.SmartmeterLoginError: Login failed. Check username/password.


But user/password did not change...
Any ideas what is wrong here?

Thanks,
H.

**Comment by h9lmut** [comment]
FYI - update to latest sources and restart of HA solved the issue for me.

**Comment by DarwinsBuddy** [comment]
I'll close this for now. Reopen when it's getting an issue again.
