### ISSUE TITLE
 Updating wnsm sensor took longer than the scheduled update interval 0:15:00 

### ISSUE THREAD

**Issue by reox** [DarwinsBuddy/WienerNetzeSmartmeter#28]
I noticed this the first time in the log.
I constantly get errors like ` Update of sensor.at10.... is taking over 10 seconds` but that one is new.

The API is actually quite slow, but it seems that in this case, it hang in a request for over 15min - at least that is what I can reconstruct from the logfiles. 🤯

Probably it is a good idea to set a timeout in `requests.Session.request` to like 60s?

**Comment by DarwinsBuddy** [comment]
could you rebase or cherry pick https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/pull/20/commits/47f024d2f7f6aa8d3245f5f003d30266ee2f18f5 onto main? Better to fix that in a separate commit immediately.

**Comment by reox** [comment]
lol, WSTW is apparently testing this feature right now, because since an hour or so I get in the logs:
```
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wstw.at', port=443): Read timed out. (read timeout=60.0)
```

the SM website is also not working... So can confirm, the fix works :D

**Comment by DarwinsBuddy** [comment]
Thanks a lot for your effort!

**Comment by stefanschramek** [comment]
Hi guys!
I have the same issue and the value is not updating anymore since this errors started showing!
<img width="568" alt="error" src="https://user-images.githubusercontent.com/921342/224538561-6579144f-0c01-43bd-ac10-68623bd20960.png">
Any idea how to solve this?
I am already on there latest version...
Thanks in advance!

**Comment by reox** [comment]
Maybe something else is running into timeouts than the requests? Can you enable the debug log and check if there is something in the logs?

**Comment by stefanschramek** [comment]
> Maybe something else is running into timeouts than the requests? Can you enable the debug log and check if there is something in the logs?

I activated debug for the integration and cleared the log afterwards.
It shows only this warning...
<img width="919" alt="error" src="https://user-images.githubusercontent.com/921342/224543015-cea76b5f-7619-4817-8ddb-bb9d9371bcf7.png">
Anything else I can take a look at to find the reason?

**Comment by DarwinsBuddy** [comment]
It seems that a request timed out.
This could be the case if

* your internet connection ist not stable at that point in time
* Wiener Netze are/were unreachable (but I guess you've tried it several times)
* the integration awaits a response where none will return (very unlikely)

If you can sort out above reasons (on your side) I am out of ideas.

I remember we introduced a time out @reox right? is that already on master?

I can double check if all requests have a time out set.

@stefanschramek which version of home assistant and wnsm integration are you running?

**Comment by stefanschramek** [comment]
I am using the following:

- HA 2023.2.5
- wnsm 1.0.3

Actually I restarted the app - as it is running as TrueCharts app on TrueNAS SCALE and also restarted the NAS (for other reasons). It now shows the sum for the values for the missing days which is fine.

If it happens again I try to dig more in this...

Thanks for the quick response!

**Comment by DarwinsBuddy** [comment]
what could also be a reason that you over provisioned your NAS, which may be struggling with all your applications additionally to home assistant

**Comment by stefanschramek** [comment]
> what could also be a reason that you over provisioned your NAS, which may be struggling with all your applications additionally to home assistant

Actually I have a pretty decent server CPU and 128GB RAM where around 60GB is free...
