### ISSUE TITLE
Entity loading error with 1.7

### ISSUE THREAD

**Issue by elmartinoAT** [DarwinsBuddy/WienerNetzeSmartmeter#284]
Also with v 1.7 i had problems to load my 2 meters, only one entity shown after updating to 1.7

```
Protokolldetails (FEHLER)
Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:728
Integration: Sensor ([Dokumentation](https://www.home-assistant.io/integrations/sensor), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
Erstmals aufgetreten: 03:29:47 (1 Vorkommnisse)
Zuletzt protokolliert: 03:29:47

wnsm: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/wnsm/wnsm_sensor.py", line 88, in async_update
    await async_smartmeter.login()
  File "/config/custom_components/wnsm/AsyncSmartmeter.py", line 24, in login
    return await self.hass.async_add_executor_job(self.smartmeter.login)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 157, in login
    code = self.credentials_login(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 104, in credentials_login
    raise SmartmeterLoginError("Login failed. Check username/password.")
custom_components.wnsm.api.errors.SmartmeterLoginError: Login failed. Check username/password.
```

Update:
After some restarts of HA and the HA docker now 2 entities shown for my 2 meters without errors ... Wiener Netze has not yet managed to convert my meters to optin and the option on the meters page to do this by myself are also not available. So i only get the meter update once a day at this time ... how often is the integration updating when i get optin with values every 15min?

**Comment by financelurker** [comment]
Hi!
I also updated to 1.7.0 today, and I am facing the same issue - only one entity shows up, since I deleted the _statistics entity as mentioned in the 1.7.0 release notes.

The wsnm:AT... entity does not show up after multiple HA restarts (not even after restarting the whole VM).

And unfortunately I don't see any errors regarding this component within Settings->System->Logs...

**Comment by wceleda** [comment]
Same here, updated to 1.7.0 and nothing changed

**Comment by DarwinsBuddy** [comment]
@financelurker 
the `wnsm:at001000000XXX` is not an entity that will show up.
You can check if it is properly set up by checking `Developer tools` -> `Statistics`.
Please see the [FAQs](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/discussions/19)
Make sure to include this into your Energy dashboard.

@elmartinoAT 
WienerNetze is not reporting in real-time, please see the [FAQs](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/discussions/19)
Also: if you try too often, WienerNetze will present the integration a captcha on login, which it cannot solve for you. So be patient and open up a new issue if issues persist, please.

@wceleda please follow the instructions in [FAQs](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/discussions/19)
