### ISSUE TITLE
Feature: Entity for hourly costs

### ISSUE THREAD

**Issue by real-alphamaennchen** [DarwinsBuddy/WienerNetzeSmartmeter#285]
Is it somehow possible to track the cost of the imported historical data?
I am using an hourly based electricity tariff and it would be great to track the costs in the energy dashboard.
I have an entity that represents the current costs (in ct/kWh).
Is this somehow possible?

Great work on this integration!

**Comment by DarwinsBuddy** [comment]
Hi,
yes it is.

Please checkout our FAQs for which statistics sensor you might want to use: https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/discussions/19

and the home assistant docs for your cost sensor.
(a google search responded this post https://community.home-assistant.io/t/solved-calculate-cost-for-individual-device-cost-kwh/523880/2)

**Comment by real-alphamaennchen** [comment]
But how do I get the hourly usage data out of the wnsm:atxxxx?
The rest should be no problem.

**Comment by real-alphamaennchen** [comment]
But how do I get the hourly usage data out of the wnsm:atxxxx?
The rest should be no problem.

**Comment by andreasgily** [comment]
are you referring to this issue?: https://community.home-assistant.io/t/electricity-price-cannot-be-set-when-using-an-external-statistic/610886
