### ISSUE TITLE
no statistic data since 2024.12.04

### ISSUE THREAD

**Issue by akicker** [DarwinsBuddy/WienerNetzeSmartmeter#288]
Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:737
Integration: Sensor ([Dokumentation](https://www.home-assistant.io/integrations/sensor), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
Erstmals aufgetreten: 11:27:02 (2 Vorkommnisse)
Zuletzt protokolliert: 11:27:02

wnsm: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/wnsm/api/client.py", line 187, in _get_api_key
    result = self.session.get(const.API_CONFIG_URL, headers=headers).json()
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 737, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/config/custom_components/wnsm/wnsm_sensor.py", line 88, in async_update
    await async_smartmeter.login()
  File "/config/custom_components/wnsm/AsyncSmartmeter.py", line 24, in login
    return await self.hass.async_add_executor_job(self.smartmeter.login)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wnsm/api/client.py", line 169, in login
    self._api_gateway_token, self._api_gateway_b2b_token = self._get_api_key(
                                                           ~~~~~~~~~~~~~~~~~^
        self._access_token
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/wnsm/api/client.py", line 189, in _get_api_key
    raise SmartmeterConnectionError("Could not obtain API key") from exception
custom_components.wnsm.api.errors.SmartmeterConnectionError: Could not obtain API key

**Comment by Skaldhor** [comment]
I receive the same error, but still have data from 2024.12.05
No data received for 2024.12.06
I'm running version 1.7.0

**Comment by botanicus1210** [comment]
Hi, I think its Wiener Netze, I cant sighn into any of their services since 2 days.

**Comment by reox** [comment]
This might be the reason:
![image](https://github.com/user-attachments/assets/66adc77b-f28d-41c7-b5ae-e1624a4fc2bd)

**Comment by DarwinsBuddy** [comment]
thanks @reox for checking. let's close this an reopen if the issue persists

**Comment by reox** [comment]
Could be something different? The official portal is back online but still no data is synced... I reopen. Let me know if you have problems too!

**Comment by W-M-B** [comment]
Still works for me. 1 meter

**Comment by Skaldhor** [comment]
Works for me again, all missing data from the last days also got imported, no change was needed from my side.

**Comment by reox** [comment]
ah okay, thanks for the feedback! 
in this case I close it again ;) Then maybe my meter needs some extra time :D

**Comment by opb1978** [comment]
@reox I have just tried the login again, still not working. The log.wien login works without a problem with my password and if I try this in the plugin for homeassistant the login still fails..

**Comment by akicker** [comment]
Up to 2024.12.04 I could trace 2 entities per Zählpunkt (at001000000000000000100000xxxxxxx AND at001000000000000000100000xxxxxxx**_statistics**. Now the entity **_statistics** shows: Diese Entität wird nicht mehr von der „wnsm"-Integration bereitgestellt. Wenn die Entität nicht mehr verwendet wird, lösche sie in den Einstellungen. 
Is this entity obsolete?

**Comment by Skaldhor** [comment]
@akicker As far as I understood, this is obsolete since v1.7.0, see [FAQ](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/discussions/19#:~:text=(Since%20v1.7.0)%20Why%20is%20my%20_statistics%20sensor%20not%20updated%20any%20longer%20with%20historical%20data%3F) also.
Since v1.7.0 there's a new entity `wnsm:ATXXXXXXXXXXXXXX` in use for tracking and you should refer to this one.

**Comment by akicker** [comment]
thx 👍
