### ISSUE TITLE
Make URL constants configurable

### ISSUE THREAD

**Issue by streilu** [DarwinsBuddy/WienerNetzeSmartmeter#37]
Maybe you can make the URLs configurable from the UI, because most of the energy companies are using the same API for smartmeter data.
Would be nice, so there would be no need to fork the repository for example in my case.

**Comment by DarwinsBuddy** [comment]
Which smart meter API do you want to call and how do you know that this is exactly the same API as of Wiener Netze?

**Comment by DarwinsBuddy** [comment]
closed due to inactivity. Please reopen it again if needed.
