### ISSUE TITLE
Integration is using deprecated `DEVICE_CLASS_*` constants

### ISSUE THREAD

**Issue by frenck** [DarwinsBuddy/WienerNetzeSmartmeter#38]
This custom integration uses deprecated `DEVICE_CLASS_*` constants in its codebase.

The `DEVICE_CLASS_*` constants have been deprecated and replaced in Home Assistant Core 2021.12 (over a year ago). I would highly suggest updating/migrating this integration to the new enums.

For example, for the device classes supported by the `sensor` platform, there is now a `SensorDeviceClass` enum. So if a sensor previously used the `DEVICE_CLASS_ENERGY` constant, it should now use `SensorDeviceClass.ENERGY`. Other platforms (like `binary_sensor`, and `number`) provide similar enumerations for their supported device classes.

The migration thus only consists of replacing constants with an enumeration member and is, therefore, very low impact and should be fairly straightforward.

If I can help resolve any questions regarding this change or migration, feel free to ask or respond to this issue. I'm happy to help!

Kindest regards,

../Frenck

**Comment by TheRealVira** [comment]
Ah good idea! Thanks for the insight, I might migrate it as soon as I am not sick anymore 🤧

**Comment by frenck** [comment]
Oh no! Get well soon 🚑 🩹

**Comment by DarwinsBuddy** [comment]
Thanks @frenck for this valuable input.

Get well soon @TheRealVira :pill:

**Comment by frenck** [comment]
Awesomely fast resolved! Thanks!

Happy New Year 🥂 

../Frenck

**Comment by HSteindl** [comment]
Excuse me being a total newbie, this is my first GIT comment ever (and I am no coder at all)
While you awesome guys are at it:
Similar to what you did in https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/pull/39  
I think you might want to also change the Energy units "kWh" over to the new enum.

In File wnsm/sensor.py 

change line 19
OLD: 	ENERGY_KILO_WATT_HOUR, 
NEW   	UnitOfEnergy, 

in Line 97 and 98
OLD: "ENERGY_KILO_WATT_HOUR"
NEW: "UnitOfEnergy.KILO_WATT_HOUR"

This has change has been introduced by https://github.com/home-assistant/core/commit/842cb18d3948709fcb1579535d38cfc28356dfda 

@frenck seems to be the man knowing if I am talking total BS or if it is worthwhile.

Thanks to all!
HST

**Comment by frenck** [comment]
@HSteindl Yes, you are right. We have many more new enums around and many more constants that have been deprecated (like all state class and unit constants). However, those have been introduced relatively recently.

For example, the energy enum you are referring to has been introduced in Home Assistant Core 2022.11 for the first time, and we still need to complete the entire migration in Core at this point.

That said, if a custom integration starts using those now, it would mean that for anyone using an older version of Home Assistant (before 2022.11), the custom integration would break.

For Core development, we have the advantage of not having to support multiple Home Assistant like custom integrations.

../Frenck

**Comment by DarwinsBuddy** [comment]
Hi @HSteindl and  @frenck 

Thanks a lot for your input and your participation.

@HSteindl no need for an excuse, any contribution or input is welcome. Especially if it's something we are currently not aware of dealing with. e.g. dealing with changes in Home Assistant.

I'm trying to keep track of the changes in Home Assistant, but lack the time currently to look at all the release notes.

@frenck What would be your suggestion to look at when it comes to deprecation and new developments, summarized in a easily digestible manner, so we can inform ourselves and document it properly in this project?
