### ISSUE TITLE
Energy Dashboard takes wrong date (+1 day) for displaying consumption delta

### ISSUE THREAD

**Issue by schoeberlt** [DarwinsBuddy/WienerNetzeSmartmeter#43]
Hi,

I noticed that the energy dashboard is one day off displaying the daily consumption data. I suppose this happens because

1. Integration gets the meter value for yesterday (at least for me) between 12:00-14:00
2. HA says "alright, so **today's** consumption is **meter value latest - meter value latest-1**" even though that's **yesterday's** consumption

Please see the screenshots for more details. I am not sure if this is related to this integration or rather to the way HA calculates delta values for aggregated sensors. I am still researching how I can change this behaviour for a particular entity in HA.

<img width="1176" alt="Screenshot 2023-01-11 at 14 33 43" src="https://user-images.githubusercontent.com/15311992/211823052-ae8b4297-07a1-473d-af7c-ff3333c43bec.png">
<img width="696" alt="Screenshot 2023-01-11 at 14 31 50" src="https://user-images.githubusercontent.com/15311992/211823060-2e3d50e6-21b0-4dc9-b6ff-ac0e8b8ab036.png">
<img width="816" alt="Screenshot 2023-01-11 at 14 37 18" src="https://user-images.githubusercontent.com/15311992/211823065-aaf63e94-f33f-410a-9818-bbc1371d66d0.png">

**Comment by HSteindl** [comment]
Thanks for posting this. Over here it is exactly the same, I see the energy usage of the current day already in the early morning. ;-)
![grafik](https://user-images.githubusercontent.com/102025015/212069615-791aeaa2-b862-4db6-8705-5dc93215e119.png)
Once in a while it also misses a day. Then the following day has double to consumption. 
take a look here:
![grafik](https://user-images.githubusercontent.com/102025015/212069844-7558cfb6-09a2-422d-bff2-a8736dc76167.png)
I dont see any hickups on my side, so maybe the API-server on the other end was down?

**Comment by schoeberlt** [comment]
I am pretty sure it's an issue with the API. However, I'd have to dig in myself into the code and checkout the API if they e.g. send a date with the daily update, because seemingly HA is simply taking the time and date of the successful request to save the data.

**Comment by reox** [comment]
The problem is, that Homeassistant takes the value as if it produced at the moment of the sensor-update. I.e., if you fetch the data on 14:23, it will say you used x kWh at 14:23...
I tried to tackle this issue by importing statistics data (See #8 ) but that introduces other issues...

Right now, there is no way to fix this - as it would require some way of back-dating values in HA.

**Comment by DarwinsBuddy** [comment]
Unfortunately @reox is right. :cry:
