### ISSUE TITLE
Entity is not updating

### ISSUE THREAD

**Issue by andreasr-vie** [DarwinsBuddy/WienerNetzeSmartmeter#50]
Hi @DarwinsBuddy 
I have the issue, that the entity is not updating. When adding the lines to configuration.yaml and secrets.yaml, I get the actual Zählerstand of my smart meter but after that the entity is never updating.
Do you have any ideas why this is not working?
Many thanks!
Andreas

**Comment by DarwinsBuddy** [comment]
Please provide some logs. Without, we can only guess what's happening.

**Comment by andreasr-vie** [comment]
I dont see anything relevant in the logs.
But before searching in the logs deeper I have another - hopefully easier - question: how often the value of the Zählerstand is being refreshed by your addon?
Many thanks!

**Comment by DarwinsBuddy** [comment]
> I dont see anything relevant in the logs.
> But before searching in the logs deeper I have another - hopefully easier - question: how often the value of the Zählerstand is being refreshed by your addon?
> Many thanks!

There is usually nothing in the logs if everything works as expected.

every hour the sensor tries to fetch new data from the API, which usually provides it somewhen the next day.

please see our FAQs for further details.

**Comment by andreasr-vie** [comment]
When opening the entity of the Zählerstand and go to tab "Info", I can see that the last update was (the screenshot is from just now) 2 hours ago.
![image](https://user-images.githubusercontent.com/114869961/215277313-2fc2f3c8-3f25-4668-bd6f-22b9dd592413.png)
Is that normal and tomorrow will be the zählerstand of the past day (today)?

**Comment by DarwinsBuddy** [comment]
Thanks @andreasr-vie for reminding me that the FAQs are missing a crucial point, namely when the data gets updated.

Please see [FAQs](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/discussions/19)
> ### How often are the sensors updated?
> This integration uses the Wiener Netze B2C API, which serves at earliest your smart meter readings
> in the morning at the day after your consumption. The integration checks every hour if new data is available and will > update
> automatically. If you have a brand new smart meter give the API a few days to expose your data.

Since yours got updated 2 hours ago, it seems everything works fine.
