### ISSUE TITLE
Integration is not working any more as WienerNetze API changed

### ISSUE THREAD

**Issue by acdcnow** [DarwinsBuddy/WienerNetzeSmartmeter#52]
This error originated from a custom integration.

Logger: custom_components.wnsm.sensor
Source: custom_components/wnsm/sensor.py:179
Integration: WienerNetzeSmartmeter (documentation, issues)
First occurred: 04:44:55 (1 occurrences)
Last logged: 04:44:55

Error retrieving data from smart meter api
Traceback (most recent call last):
  File "/config/custom_components/wnsm/sensor.py", line 231, in async_update
    welcome = await self.get_welcome(smartmeter)
  File "/config/custom_components/wnsm/sensor.py", line 179, in get_welcome
    raise RuntimeError("Cannot access welcome: ", response)
RuntimeError: ('Cannot access welcome: ', {'Exception': 'PROD API Gateway encountered an error. Error Message: Resource /zaehlpunkt/default/welcome not found. Request Details: Service - WN_SMART_METER_PORTAL_API_B2C, Operation - null, Invocation Time:3:44:54 AM, Date:Feb 17, 2023,  Client IP - xxxxxxx, User - Default and Application:null'})

Checking smartmeter homepage show the smartmeter dat even if they have not been updates since 2 months which is an other issue but from WN this time.
Have they changed the API again?

**Comment by cleversmart** [comment]
same here, but with 2022.12.8, it seams like it‘s the API…

**Comment by adamnet01** [comment]
Hi, It's not working for me either.

Logger: custom_components.wnsm.sensor
Source: custom_components/wnsm/sensor.py:179
Integration: WienerNetzeSmartmeter (documentation, issues)
First occurred: 06:25:15 (20 occurrences)
Last logged: 11:02:32

Error retrieving data from smart meter api
Traceback (most recent call last):
  File "/config/custom_components/wnsm/sensor.py", line 231, in async_update
    welcome = await self.get_welcome(smartmeter)
  File "/config/custom_components/wnsm/sensor.py", line 179, in get_welcome
    raise RuntimeError("Cannot access welcome: ", response)
RuntimeError: ('Cannot access welcome: ', {'Exception': 'PROD API Gateway encountered an error. Error Message: Resource /zaehlpunkt/default/welcome not found. Request Details: Service - WN_SMART_METER_PORTAL_API_B2C, Operation - null, Invocation Time:5:25:15 AM, Date:Feb 17, 2023,  Client IP - 212.17.110.118, User - Default and Application:null'})

**Comment by reox** [comment]
sounds like the `/zaehlpunkt/default/welcome` endpoint is gone...

Seems like it is split up now into several calls:
`https://api.wstw.at/gateway/WN_SMART_METER_PORTAL_API_B2C/1.0/zaehlpunkt/consumptions` returns:
```
{
    "consumptionYesterday": {
        "value": 3300,
        "validated": true,
        "date": "2023-02-15T23:00:00.000Z"
    },
    "consumptionDayBeforeYesterday": {
        "value": 4049,
        "validated": true,
        "date": "2023-02-14T23:00:00.000Z"
    }
}
```

and `https://api.wstw.at/gateway/WN_SMART_METER_PORTAL_API_B2C/1.0/zaehlpunkt/baseInformation` returns:
```
{
    "hasSmartMeter": true,
    "isDataDeleted": false,
    "dataDeletionTimestampUTC": null,
    "zaehlpunkt": {
        "zaehlpunktName": null,
        "zaehlpunktnummer": "...",
        "zaehlpunktAnlagentyp": "TAGSTROM",
        "adresse": "...",
        "postleitzahl": "..."
    }
}
```

IIRC these were the contents of the `welcome` endpoint before.

**Comment by DarwinsBuddy** [comment]
Thanks @reox for investigating. Will have a look

**Comment by DarwinsBuddy** [comment]
Fixed and rolled https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/releases/tag/v1.0.2

**Comment by DarwinsBuddy** [comment]
@acdcnow Thanks a lot for reporting this in such a detailed manner and @reox for the quick analysis. :)
