### ISSUE TITLE
AttributeError: 'datetime.datetime' object has no attribute 'timedelta'

### ISSUE THREAD

**Issue by mlocher** [DarwinsBuddy/WienerNetzeSmartmeter#53]
Hey there, 

I'm not sure if this is the best, or even the right place to report this. If it isn't, please let me know.

I was trying to configure the WienerNetze integration, and noticed the `v1.0.2` release 2 days ago. After updating via HACS, I now the get the following error. 

I am not familiar with Python. I tried googling the error, but that didn't bring up any useful results. I looked into the Python documentation, but didn't find anything obvious either. I'd be grateful for any pointers on what might be causing this and how to fix it.

Home Assistant 2023.2.5 (Running as a Docker container)
Frontend 20230202.0 - latest
HACS 1.30.1
wnsm v1.0.2

Logs:
```
Logger: homeassistant.components.sensor
Source: custom_components/wnsm/utils.py:24
Integration: Sensor (documentation, issues)
First occurred: 8:31:54 PM (1 occurrences)
Last logged: 8:31:54 PM

wnsm: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    await task
  File "/config/custom_components/wnsm/sensor.py", line 269, in async_update
    smartmeter, before(today())
  File "/config/custom_components/wnsm/utils.py", line 24, in before
    return datetime - datetime.timedelta(days=days)
AttributeError: 'datetime.datetime' object has no attribute 'timedelta'
```

**Comment by DarwinsBuddy** [comment]
Thanks for reporting. On it

**Comment by DarwinsBuddy** [comment]
Fixed in https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/releases/tag/v1.0.3
