### ISSUE TITLE
outage agnostic support

### ISSUE THREAD

**Issue by DarwinsBuddy** [DarwinsBuddy/WienerNetzeSmartmeter#7]
Every now and then WN doesn't return any data or due to a sensor error we may miss days of usage.

Extend the sensor, s.t. it somehow recognizes which days have been missed since the setup of the sensor and try to pull them retrospectively

**Comment by andreasgily** [comment]
Maybe it would be a workaround to add the 30-day average daily consumption value just before midnight, if no data could be fetched... this would smoothen out at least this spikes.

**Comment by DarwinsBuddy** [comment]
I updated your comment, please use `code blocks` next time for better readability.
the avg will not represent the actual consumption unfortunately, I made the compromise already by interpolating missing data with the avg of the day, but doing that for longer periods of time will result in the sensor to drift apart from the actual consumption pretty fast imho.

**Comment by DarwinsBuddy** [comment]
covered in https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/pull/101

closing this
