### ISSUE TITLE
Unable to prepare setup for platform wnsm.sensor

### ISSUE THREAD

**Issue by thecalicojack** [DarwinsBuddy/WienerNetzeSmartmeter#71]
I get the following error after adding the WNSM integration:

Logger: homeassistant.setup
Source: setup.py:320
First occurred: 16:33:29 (1 occurrences)
Last logged: 16:33:29

Unable to prepare setup for platform wnsm.sensor: Platform not found (cannot import name 'UnitOfEnergy' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

**Comment by DarwinsBuddy** [comment]
How did you install the integration?
HACS or manual?

which version of home assistant are you running?

which version of wnsm are you trying to install?

**Comment by thecalicojack** [comment]
I installed it via HACS
The wnsm version is 1.0.3
HA version:  Home Assistant 2022.10.5; Frontend 20221010.0 - latest 

Actually the the wnsm already worked in the past. I think until i updated it from 1.0.1 to 1.0.3

**Comment by thecalicojack** [comment]
Updating Home Assistant to the current version solved the problem.
Thanks for your quick answer anyway.
