### ISSUE TITLE
sensor.at00100... with attribute Longitude and Latitude overrides the home zone in the default map.

### ISSUE THREAD

**Issue by Sup3rMario** [DarwinsBuddy/WienerNetzeSmartmeter#82]
Sensors with the Longitude and Latitude attribute are displayed on the map in the Home Assistant by default. Can you delete these attributes or make them switchable? The icon overrides the home zone.
![Home Assistant Sensor Wien Energie](https://user-images.githubusercontent.com/10222176/227705563-7f6fffe3-f90e-4fbf-8caa-359da03939d8.jpg)
![Home Assistant Karte Wien Energie](https://user-images.githubusercontent.com/10222176/227705568-24972ab7-8b63-46b4-9a8b-7c6be5701a89.jpg)

**Comment by DarwinsBuddy** [comment]
afaik this is merely the location reported by the sensor. If you want to have a home zone configures you can do so by navigating to `https://<hassio>/config/general`. For me I have a home zone and an icon for the sensor, but they do not interfere, but are just both shown on the same spot on the map when zoomed out far enough.

**Comment by DarwinsBuddy** [comment]
see https://www.home-assistant.io/docs/configuration/basic/
