### ISSUE TITLE
Data is collected incorrectly (date shifted by one day)

### ISSUE THREAD

**Issue by Sup3rMario** [DarwinsBuddy/WienerNetzeSmartmeter#84]
If I compare the data in the Home Assistant and on the Smartmeter website, the data in the Home Assistant is shifted back by one day, i.e. the 10.515 kWh from Friday appear in the Home Assistant on Saturday and the 11.313 kWh from Saturday appear in the Home Assistant on Sunday . Thus, the weekly total data displays are not correct! (see printscreens)
Please check it.
![ScreenShot 20230326-135942](https://user-images.githubusercontent.com/10222176/227774601-7b6f2d78-7c28-4e34-813d-296964f5f38a.PNG)
![ScreenShot 20230326-135915](https://user-images.githubusercontent.com/10222176/227774603-d8067081-e6af-496c-8794-db92d242c577.PNG)
![ScreenShot 20230326-135848](https://user-images.githubusercontent.com/10222176/227774604-bec3d2ee-3a58-4d8b-8223-eee7caea238b.PNG)

**Comment by reox** [comment]
Are you using the code from the PR #35 ?
Otherwise that is normal behavior as the meter reading is delayed by 24h by the API.

**Comment by Sup3rMario** [comment]
Sorry, I'm a beginner on Home Assistant and I installed the HACS version. How can I change that?
Can't you correct the date in the script? Unfortunately, Wiener Netze only provides the data once a day via the web portal. Can you also read in the csv file from the data export (every 15 minutes) with your script? But they are only available for the previous day!
