### ISSUE TITLE
15Min Opt-In Unit of Measurement

### ISSUE THREAD

**Issue by gluckb** [DarwinsBuddy/WienerNetzeSmartmeter#9]
I just realized my values are wrong.
The sensor read 9533 which was shown as 9.533 on the dashboard.
It should be 9,533 kWh.

I divided the sum by 1000 in line 183:
s = sum([y["value"] if y["value"] is not None else avg for y in yesterdays_consumption["values"]]) / 1000

**Comment by DarwinsBuddy** [comment]
do you want to provide a pull request for your changes?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Is this fixed?

**Comment by DarwinsBuddy** [comment]
I am not sure if this is still an issue. @gluckb never replied back and I am not sure if it was a real issue in the first place.
@h0jeZvgoxFepBQ2C do you have a similar issue? I get the right units reported by the integration.

**Comment by TheRealVira** [comment]
Same here. I can't reproduce this issue.

**Comment by DarwinsBuddy** [comment]
closed due to inactivity. Please reopen it again if needed.
